name: Build EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # 你可以根据需要更改Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build EXE
      run: pyinstaller --onefile send_qq_message.py

    - name: Upload EXE
      uses: actions/upload-artifact@v2
      with:
        name: clipboard-checker
        path: dist/send_qq_message.exe
