name: Build EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyqt5 pyqt5-tools pyautogui
    - name: Build EXE
      run: pyinstaller --onefile send_qq_message.py
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: exe-file
        path: dist/
